In [7]:
import numpy as np
import pandas as pd

In [8]:
dict1={
    "name":["harry","rohan","skillf","shubh"],
    "marks":[92,12,33,53],
    "city":["rampur","kolkata","bareilly","antarctica"]
}

In [9]:
df=pd.DataFrame(dict1)

In [10]:
df.to_csv("friends.csv")

In [11]:
df.to_csv("friends_index_false.csv",index=False)

In [12]:
df.head(3)

     name  marks      city
0   harry     92    rampur
1   rohan     12   kolkata
2  skillf     33  bareilly

In [13]:
df.tail(2)

     name  marks        city
2  skillf     33    bareilly
3   shubh     53  antarctica

In [14]:
df.describe()

           marks
count   4.000000
mean   47.500000
std    34.063666
min    12.000000
25%    27.750000
50%    43.000000
75%    62.750000
max    92.000000

In [15]:
adi=df.read_csv("train.csv")

AttributeError: 'DataFrame' object has no attribute 'read_csv'

In [ ]:
adi=pd.read_csv("train.csv")

In [16]:
adi

NameError: name 'adi' is not defined

In [17]:
adi["speed"]

NameError: name 'adi' is not defined

In [18]:
adi["speed"][0]=50

NameError: name 'adi' is not defined

In [19]:
adi

NameError: name 'adi' is not defined

In [ ]:
adi["speed"][0] = 50

In [20]:
adi.loc[0, "speed"] = 50

NameError: name 'adi' is not defined

In [21]:
harry=pd.read_csv("train.csv")

In [22]:
harry

   Train no  speed        city
0     12334     92      rampur
1     23422     87     kolkata
2     12434     56    bareilly
3     23423     78  antarctica

In [23]:
harry["speed"][0] = 50

C:\Users\soumik\AppData\Local\Temp\ipykernel_16928\1962742037.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  harry["speed"][0] = 50

In [24]:
harry

   Train no  speed        city
0     12334     92      rampur
1     23422     87     kolkata
2     12434     56    bareilly
3     23423     78  antarctica

In [25]:
df.to_csv("train.csv",index=False)

In [26]:
df

     name  marks        city
0   harry     92      rampur
1   rohan     12     kolkata
2  skillf     33    bareilly
3   shubh     53  antarctica

In [27]:
haryy

NameError: name 'haryy' is not defined

In [28]:
harry

   Train no  speed        city
0     12334     92      rampur
1     23422     87     kolkata
2     12434     56    bareilly
3     23423     78  antarctica

In [29]:
harry.to_csv("train.csv",index =False)

In [30]:
harry

   Train no  speed        city
0     12334     92      rampur
1     23422     87     kolkata
2     12434     56    bareilly
3     23423     78  antarctica

In [31]:
 harry.index=["first","second","third","fourth"]

In [32]:
harry

        Train no  speed        city
first      12334     92      rampur
second     23422     87     kolkata
third      12434     56    bareilly
fourth     23423     78  antarctica

In [33]:
sr=pd.Series(np.random.rand(34))

In [34]:
sr

0     0.428695
1     0.435941
2     0.556662
3     0.000753
4     0.427151
5     0.770615
6     0.988489
7     0.881265
8     0.632548
9     0.045892
10    0.654374
11    0.976917
12    0.579223
13    0.955945
14    0.256529
15    0.514456
16    0.238095
17    0.194291
18    0.128476
19    0.424915
20    0.648288
21    0.970400
22    0.643248
23    0.387562
24    0.150948
25    0.315193
26    0.558033
27    0.360556
28    0.339171
29    0.914573
30    0.698483
31    0.686473
32    0.644611
33    0.693260
dtype: float64

In [35]:
type(sr)

pandas.Series

In [36]:
newdf=pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [37]:
newdf.head()

          0         1         2         3         4
0  0.130340  0.485808  0.131965  0.587107  0.654741
1  0.634796  0.759679  0.736930  0.601172  0.229649
2  0.804179  0.933052  0.675194  0.829304  0.494099
3  0.346147  0.810308  0.122496  0.759406  0.085348
4  0.966907  0.348734  0.432317  0.386624  0.104018

In [38]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.493921    0.469711    0.510748    0.480035    0.502008
std      0.294921    0.282294    0.295628    0.284570    0.272469
min      0.002178    0.003692    0.000568    0.004425    0.002389
25%      0.227752    0.236220    0.258638    0.220128    0.284041
50%      0.491205    0.467640    0.519851    0.483514    0.510268
75%      0.770859    0.693106    0.776020    0.720514    0.719244
max      0.998401    0.993590    0.999059    0.982746    0.994790

In [39]:
newdf[0][0] = "harry"

C:\Users\soumik\AppData\Local\Temp\ipykernel_16928\2771891818.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newdf[0][0] = "harry"

TypeError: Invalid value 'harry' for dtype 'float64'

In [ ]:
newdf.dtype

In [ ]:
newdf.dtypes

In [ ]:
newdf[0][0] = "harry"

In [ ]:
newdf

In [ ]:
newdf[0] = "harry"

In [ ]:
newdf

In [ ]:
newdf[0][0] ="adii"

In [ ]:
newdf.loc[0, 0] = " adii"

In [ ]:
newdf.head()

In [ ]:
newdf.dtypes

In [ ]:
newdf.columns

In [ ]:
newdf.to_numpy()

In [ ]:
newdf.T

In [ ]:
newdf.sort()

In [ ]:
newdf.sort_index(axis = 0, ascending=False)

In [ ]:
newdf[0]

In [ ]:
type(newdf[0])

In [ ]:
newdf.loc[1,0] = "harrish"

In [ ]:
newdf

In [ ]:
newdf.columns=list("ABCDE")

In [ ]:
newdf.head()

In [ ]:
newdf.rows=list("abcde")

In [ ]:
newdf.drop("E",axis= 1)

In [ ]:
newdf.loc[[1,2], : ]

In [ ]:
newdf.loc[(newdf["B"]>0.6)]

In [ ]:
newdf.loc[(newdf["B"]>0.6) & (newdf["C"]<0.3)]

In [ ]:
 newdf.drop(newdf[0])

In [ ]:
newdf.drop([0])

In [ ]:
newdf.drop(["A","D"], axis=1)

In [ ]:
newdf.drop(["A","D"], axis=1, inplace=True)

In [ ]:
newdf

In [ ]:
newdf.drop([1,5], axis=0)

In [ ]:
newdf.reset_index(drop=True, inplace=True)

In [ ]:
newdf.head(4)

In [ ]:
newdf["B"].isnull()

In [ ]:
newdf.loc[ :,["B"]]= None

In [ ]:
data ={
   'date':],[pd.Timestamp('2023-01-01'), pd.NaT, pd.Timestamp('2023-01-03')],
   'value':[10, 20, 30]

In [ ]:
newdf.dropna(how="all", axis=1)

In [ ]:
df = pd.DataFrame({
    "name": ["A", "B", "C", "D", None],
    "age": [20, None, 25, 30, 22],
    "speed": [10, 20, None, 40, None]
})

In [ ]:
df

In [ ]:
df.drop_duplicates(subset=["name"],keep=False)

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.info()

In [ ]:
df.info()

In [ ]:
df.shape

In [49]:
df.drop_duplicates(subset=["name"],keep=False)

     name  marks        city
0   harry     92      rampur
1   rohan     12     kolkata
2  skillf     33    bareilly
3   shubh     53  antarctica

In [50]:
df.head()

     name  marks        city
0   harry     92      rampur
1   rohan     12     kolkata
2  skillf     33    bareilly
3   shubh     53  antarctica

In [51]:
df.head(2)

    name  marks     city
0  harry     92   rampur
1  rohan     12  kolkata